### ISSUE TITLE
Hyperlinks in documentation are broken without ECMAScript

### ISSUE THREAD

**Issue by emixa-d** [zyrolasting/xiden#36]
Take <https://docs.racket-lang.org/xiden-guide/index.html> for example, more specifically the link in ‘For all documentation, see Xiden Documentation.’.
Following that link leads to the following error page:

Redirections

This page is intended to redirect to the result of a search request. Since you’re reading this, it seems that the redirection did not work.

**Comment by zyrolasting** [comment]
Reproduced. This is an artifact of how Scribble manuals work with Racket. Try opening this with https://github.com/racket/scribble/issues
